apiVersion: apps/v1
kind: Deployment
metadata:
  name: page-blue-deployment
spec:
  selector:
    matchLabels:
      app: page-blue
  template:
    metadata:
      labels:
        app: page-blue
    spec:
      containers:
        - name: page-blue
          image: fabricioveronez/web-page:blue
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 80